### ISSUE TITLE
Model download link is broken

### ISSUE THREAD

**Issue by Gyubin** [fmahoudeau/MiCT-RANet-ASL-FingerSpelling#1]
Hi @fmahoudeau 
The download link of model ([MiCT-RANet34](https://1drv.ms/u/s!AvyZUg7UPo_CgdN4QBbq4I85Cl25Ww?e=KY07YI)) is broken.
I would be grateful if you could restore the link.
Thank you for the great work.

**Comment by becxer** [comment]
I am also eagerly looking for the checkpoint of this model!

**Comment by Gyubin** [comment]
Sorry. The link works well.

**Comment by deepaktammali** [comment]
I am not able to download the model, how were you able to download it?

**Comment by fmahoudeau** [comment]
Here's a new checkpoint link for downloading:
https://drive.proton.me/urls/3QC326KREG#owB6r4GkFdbN
